server:
    port: 50050
    
spring:
    application:
        name: chatroomcreator
    profiles:
        active:
            default
    session:
        storage-type: redis
    redis:
        host: localhost
        port: 6379

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/