server:
    port: 50052
    
spring:
    application:
        name: receiveservice
    profiles:
        active:
            default

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
