server:
    port: 8888

spring:
    application:
        name: configserver
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri: https://github.com/zzzinho/MSA-chatting
                    searchPaths: config/chatroomcreator, config/chatroomreader, config/messagepublisher, config/messagesubscriber, config/userkicker
                encrypt.enabled: true

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka:  true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka