server:
    port: 50051
    
spring:
    application:
        name: sendservice
    profiles:
        active:
            default

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/